// src/utils/banks.ts

export const BANKS = [
  { id: 1, nome: "BANCO DO BRASIL", numero: "001" },
  { id: 2, nome: "BANCO SANTANDER", numero: "033" },
  { id: 3, nome: "BANCO NOSSA CAIXA", numero: "151" },
  { id: 4, nome: "CEF-CAIXA ECONÔMICA FEDERAL", numero: "104" },
  { id: 5, nome: "BRADESCO", numero: "237" },
  { id: 6, nome: "BANCO ITAÚ", numero: "341" },
  { id: 7, nome: "HSBC", numero: "399" },
  { id: 8, nome: "UNIBANCO", numero: "409" },
  { id: 9, nome: "CITIBANK", numero: "477" },
  { id: 10, nome: "CRUZEIRO DO SUL", numero: "229" },
  { id: 11, nome: "BANCO CACIQUE", numero: "263" },
  { id: 12, nome: "BMG", numero: "318" },
  { id: 13, nome: "BANCO VOTORANTIM", numero: "655" },
  { id: 14, nome: "BANCO REAL", numero: "356" },
  { id: 15, nome: "BANCO BANRISUL", numero: "041" },
  { id: 16, nome: "BANCO MERCANTIL DO BRASIL", numero: "389" },
  { id: 17, nome: "BANESTES", numero: "021" },
  { id: 18, nome: "BANCO SAFRA", numero: "422" },
  { id: 19, nome: "BANCO DE BRASÍLIA", numero: "070" },
  { id: 20, nome: "BANCO SICREDI", numero: "748" },
  { id: 21, nome: "BANCOOB / SICOOB", numero: "756" },
  { id: 22, nome: "BANESE", numero: "047" },
  { id: 23, nome: "BANCO BMC", numero: "394" },
  { id: 24, nome: "BANCO CRUZEIRO DO SUL", numero: "229" },
  { id: 25, nome: "BRADESCARD", numero: "063" },
  { id: 26, nome: "FINANCEIRA ALFA", numero: "025" },
  { id: 27, nome: "BANCO ACREDITA", numero: "912" },
  { id: 28, nome: "BRB FINANCEIRA", numero: "070" },
  { id: 29, nome: "CREDIARE/CREDIFAR", numero: "921" },
  { id: 30, nome: "BANCO GE CAPITAL", numero: "233" },
  { id: 31, nome: "BANCO FICSA", numero: "626" },
  { id: 32, nome: "BANCO MASTER", numero: "243" },
  { id: 33, nome: "BANCO MAXIMA", numero: "224" },
  { id: 34, nome: "BANCO PARATI", numero: "908" },
  { id: 35, nome: "CETELEM", numero: "920" },
  { id: 36, nome: "BANCO BVA", numero: "044" },
  { id: 37, nome: "BANCO BONSUCESSO", numero: "218" },
  { id: 38, nome: "BANCO CACIQUE", numero: "263" },
  { id: 39, nome: "BANCO BGN", numero: "739" },
  { id: 40, nome: "BANCO ABC BRASIL", numero: "246" },
  { id: 41, nome: "BANCO SOFISA", numero: "637" },
  { id: 42, nome: "CITIBANK", numero: "745" },
  { id: 43, nome: "BANCO SOCICRED", numero: "917" },
  { id: 44, nome: "BANCO MORADA", numero: "738" },
  { id: 45, nome: "BANCO RURAL", numero: "907" },
  { id: 46, nome: "BANCO PINE", numero: "643" },
  { id: 47, nome: "BANCO BBM", numero: "107" },
  { id: 48, nome: "ASB", numero: "915" },
  { id: 49, nome: "BANCO SEMEAR", numero: "743" },
  { id: 50, nome: "BANCO SCHAHIN", numero: "250" },
  { id: 51, nome: "BANCO OBOÉ", numero: "906" },
  { id: 52, nome: "INTERMEDIUM", numero: "903" },
  { id: 53, nome: "BANCO ORIGINAL", numero: "212" },
  { id: 54, nome: "SUL FINANCEIRA", numero: "901" },
  { id: 55, nome: "BANCO PAULISTA", numero: "611" },
  { id: 56, nome: "BANCO ARBI", numero: "213" },
  { id: 57, nome: "BANCO DAYCOVAL", numero: "707" },
  { id: 58, nome: "PARANÁ BANCO", numero: "707" },
  { id: 59, nome: "BANCO BMC", numero: "394" },
  { id: 60, nome: "BANCO LECCA", numero: "922" },
  { id: 61, nome: "BANCO PAN", numero: "623" },
  { id: 62, nome: "CREFISA (INATIVO)", numero: "902" },
  { id: 63, nome: "BANCO INDUSTRIAL", numero: "604" },
  { id: 64, nome: "BANPARA", numero: "037" },
  { id: 65, nome: "BANCO DA AMAZÔNIA", numero: "003" },
  { id: 66, nome: "BANCO BIC", numero: "320" },
  { id: 67, nome: "BANCO ORIGINAL AGRONEGÓCIO", numero: "079" },
  { id: 70, nome: "BMG SPI", numero: "342" },
  { id: 71, nome: "SABEMI", numero: "098" },
  { id: 72, nome: "BANCO DO NORDESTE", numero: "004" },
  { id: 73, nome: "CREDCREA", numero: "085" },
  { id: 74, nome: "ITAÚ CONSIGNADO", numero: "029" },
  { id: 76, nome: "OLÉ CONSIGNADO", numero: "955" },
  { id: 81, nome: "BANCO INTER", numero: "077" },
  { id: 85, nome: "NUBANK", numero: "260" },
  { id: 89, nome: "C6 BANK", numero: "336" },
  { id: 99, nome: "MERCADO PAGO", numero: "323" },
  { id: 100, nome: "BANCO DIGIO", numero: "335" },
  { id: 103, nome: "BANCO UP.P", numero: "373" },
  { id: 122, nome: "BANCO STONE", numero: "197" },
  { id: 123, nome: "BANCO CORA", numero: "403" },
  { id: 134, nome: "BANCO NEON", numero: "536" },
  { id: 138, nome: "BANCO DIGIMAIS", numero: "654" }
];
